services:
  - type: web
    name: milk-crm-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: ALLOWED_ORIGINS
        value: https://milk-crm.netlify.app,http://localhost:3000
